title: The AI Rocket Ship
description: intelligence.join(analytics, on=["smarts"], how="full outer")
show_downloads: false
google_analytics:
theme: jekyll-theme-dinky
classes: wide
markdown: kramdown
